### ISSUE TITLE
Не могу получить группу регулярного выражения

### ISSUE THREAD

**Issue by arturaquarius** [SpaceHead1C/1c_regexp#12]
ПроцессорРаспознавания = Регулярка.ПроцессорРаспознавания("(\d{10})\w+");
Текст = "1234567891fjnjisfiwenrfg";

Вх = Регулярка.Вхождения(ПроцессорРаспознавания, Текст);

Для Каждого В из ВХ Цикл
	Сообщить(В.Значение);
КонецЦикла;

Не могу получить группу, Регулярка.Вхождения(ПроцессорРаспознавания, Текст) возвращает только совпадение без группы.

**Comment by SpaceHead1C** [comment]
На текущий

**Comment by ndSpacehead** [comment]
На текущий момент подсистема не возвращает группы, только совпадения и их позиции в исходном тексте.
